
services:
  ms_payment:
    image: mysql:8.0
    container_name: ms_payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_payment
      MYSQL_USER: ms_payment
      MYSQL_PASSWORD: root
    ports:
      - "3312:3306"
    volumes:
      - ms_payment_data:/var/lib/mysql
volumes:
  ms_payment_data: